Repository Juanpe/SkeletonView, pull requests merged in 2021-02, with the labels that each got.

#369 remove useless corner radius constraint
  CHANGELOG.md
  README.md
  README_es.md
  Sources/Multilines/UILabel+Multiline.swift
  Sources/Multilines/UITextView+Multiline.swift
Labels: next release, 💡 enhancement

#371 fix: remove temp height constraints after hiding the skeleton
  Example/TableView/Base.lproj/Main.storyboard
  Sources/Helpers/PrepareForSkeletonProtocol.swift
Labels: 🐞 bug

#372 remove SwiftLint warnings
  Sources/Extensions/CALayer+Extensions.swift
  Sources/Extensions/UIColor+Skeleton.swift
  Sources/Helpers/AssociationPolicy.swift
  Sources/SkeletonAnimationBuilder.swift
Labels: ⚙️ maintenance

#356 Fixed: UITextField placeholder text is visible while skeleton is showing
  Example/TableView/Base.lproj/Main.storyboard
  Sources/Helpers/PrepareForSkeletonProtocol.swift
  Sources/Recoverable/Recoverable.swift
  Sources/Recoverable/RecoverableViewState.swift
Labels: 💡 enhancement

#374 update all “develop” references
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/release_notes.yml
  .github/workflows/validations.yml
  CONTRIBUTING.md
  README.md
  README_es.md
Labels: skip-changelog

#375 restore `isUserInteractionEnabled` value
  Sources/Collections/CollectionSkeletonProtocol.swift
  Sources/Extensions/UIColor+Skeleton.swift
  Sources/Helpers/PrepareForSkeletonProtocol.swift
  Sources/SkeletonView.swift
Labels: 🐞 bug

#376 Deprecation warning fix for AssociatedObjects protocol from `class` to `AnyObject`
  Sources/Helpers/AssociationPolicy.swift
Labels: 💡 enhancement
