Repository Juanpe/SkeletonView, pull requests merged in 2021-06, with the labels that each got.

#402 Fix TableViewCell skeleton not being removed & automaticNumberOfRows reference
  Sources/Collections/CollectionViews/SkeletonCollectionViewProtocols.swift
  Sources/Collections/TableViews/SkeletonTableViewProtocols.swift
  Sources/SubviewsSkeletonables.swift
Labels: 🐞 bug

#403 CI action to build targets, not just clean
  .github/workflows/main.yml
Labels: skip-changelog

#404 fix typo `isUserInteractionDisabledWhenSkeletonIsActive`
  README.md
  Sources/Collections/CollectionSkeletonProtocol.swift
  Sources/Extensions/UIView+Extension.swift
  Sources/Extensions/UIView+IBInspectable.swift
  Sources/Helpers/PrepareForSkeletonProtocol.swift
  Sources/Recoverable/Recoverable.swift
Labels: 🐞 bug

#406 fix bug remove constraints wrongly
  Sources/Extensions/UIView+Autolayout.swift
  Sources/Helpers/PrepareForSkeletonProtocol.swift
  Sources/Recoverable/Recoverable.swift
Labels: 🐞 bug

#409 Replace SkeletonCollectionDataSource.automaticNumberOfRows with UITableView.automaticNumberOfSkeletonRows and UICollectionView.automaticNumberOfSkeletonItems
  README.md
  Sources/Collections/CollectionViews/SkeletonCollectionViewProtocols.swift
  Sources/Collections/CollectionViews/UICollectionView+CollectionSkeleton.swift
  Sources/Collections/SkeletonCollectionDataSource.swift
  Sources/Collections/TableViews/SkeletonTableViewProtocols.swift
  Sources/Collections/TableViews/UITableView+CollectionSkeleton.swift
Labels: 🐞 bug

#410 Improved the algorithm that calculates the number of skeleton lines for UITextViews
  Sources/Helpers/PrepareForSkeletonProtocol.swift
  Sources/Multilines/ContainsMultilineText.swift
  Sources/Multilines/UILabel+Multiline.swift
  Sources/Multilines/UITextView+Multiline.swift
  Sources/SkeletonLayer.swift
  Sources/SkeletonView.swift
  Sources/Transitions/UIView+Transitions.swift
Labels: 💡 enhancement

#411 Delay the presentation of the skeletons
  README.md
  Sources/Extensions/UIView+Extension.swift
  Sources/SkeletonView.swift
Labels: feature

#414 Add both `skeletonCellForRowAt` and `skeletonCellForItemAt` methods
  Example/CollectionView/ViewController.swift
  Example/TableView/ViewController.swift
  README.md
  Sources/Collections/CollectionViews/SkeletonCollectionViewProtocols.swift
  Sources/Collections/SkeletonCollectionDataSource.swift
  Sources/Collections/TableViews/SkeletonTableViewProtocols.swift
Labels: feature

#415 Add `prepareCellForSkeleton` for `UITableView` and `UICollectionView`
  Example/CollectionView/ViewController.swift
  Example/TableView/ViewController.swift
  README.md
  Sources/Collections/CollectionViews/SkeletonCollectionViewProtocols.swift
  Sources/Collections/SkeletonCollectionDataSource.swift
  Sources/Collections/TableViews/SkeletonTableViewProtocols.swift
Labels: feature

#417 Fixed bg color warning in `UITableViewHeaderFooterView`
  Sources/Extensions/UIView+Extension.swift
  Sources/Helpers/PrepareForSkeletonProtocol.swift
  Sources/Recoverable/Recoverable.swift
  Sources/Recoverable/RecoverableViewState.swift
Labels: 💡 enhancement
