Repository Juanpe/SkeletonView, pull requests merged in 2021-08, with the labels that each got.

#431 Align last line of skeleton view according to text alignment
  Example/TableView/Base.lproj/Main.storyboard
  SkeletonView.xcodeproj/xcshareddata/xcschemes/SkeletonViewExample.xcscheme
  Sources/Builders/SkeletonMultilineLayerBuilder.swift
  Sources/Extensions/CALayer+Extensions.swift
  Sources/Multilines/ContainsMultilineText.swift
  Sources/SkeletonLayer.swift
Labels: 💡 enhancement

#427 Fix for bug 426
  Sources/Multilines/UILabel+Multiline.swift
Labels: 💡 enhancement

#443 Add new property `useFontLineHeight
  README.md
  SkeletonViewCore/Sources/API/UIKitExtensions/UILabel+IBInspectable.swift
  SkeletonViewCore/Sources/API/UIKitExtensions/UITextView+IBInspectable.swift
  SkeletonViewCore/Sources/Internal/SkeletonExtensions/SkeletonTextNode.swift
Labels: 💡 enhancement

#444 Improve debug description and create SkeletonExtensions
  Examples/iOS Example/Sources/ViewController.swift
  README.md
  SkeletonView.xcodeproj/project.pbxproj
  SkeletonViewCore/Sources/API/Deprecated.swift
  SkeletonViewCore/Sources/API/SkeletonExtended.swift
  SkeletonViewCore/Sources/API/UIKitExtensions/UIView+Debug.swift
  SkeletonViewCore/Sources/API/UIKitExtensions/UIView+Flags.swift
  SkeletonViewCore/Sources/API/UIKitExtensions/UIView+SKExtensions.swift
  SkeletonViewCore/Sources/Internal/Collections/SkeletonCollectionDataSource.swift
  SkeletonViewCore/Sources/Internal/Collections/SkeletonCollectionDelegate.swift
  SkeletonViewCore/Sources/Internal/Debug/SkeletonDebug.swift
  SkeletonViewCore/Sources/Internal/SkeletonFlowHandler.swift
  SkeletonViewCore/Sources/Internal/SkeletonTree/SkeletonTreeNode.swift
  SkeletonViewCore/Sources/Internal/UIKitExtensions/SkeletonTreeNode+Extensions.swift
  SkeletonViewCore/Sources/Internal/UIKitExtensions/UIView+AppLifecycleNotifications.swift
  SkeletonViewCore/Sources/Internal/UIKitExtensions/UIView+Extensions.swift
  SkeletonViewCore/Sources/Internal/UIKitExtensions/UIView+SkeletonView.swift
  SkeletonViewCore/Sources/Internal/UIKitExtensions/UIView+Swizzling.swift
Labels: ⚙️ maintenance

#446 make skeletonPaddingInsets public again
  SkeletonView.xcodeproj/project.pbxproj
  SkeletonViewCore/Sources/API/UIKitExtensions/UILabel+SKExtensions.swift
  SkeletonViewCore/Sources/API/UIKitExtensions/UITextView+SKExtensions.swift
  SkeletonViewCore/Sources/Internal/UIKitExtensions/UILabel+Extensions.swift
Labels: 🐞 bug
